/*
    Ejercicio 8.
*/
CREATE PUBLIC SYNONYM CO_ACUDIENTE FOR COLEGIO.ACUDIENTE;
CREATE PUBLIC SYNONYM CO_ASIGNATURA FOR COLEGIO.ASIGNATURA;
CREATE PUBLIC SYNONYM CO_CARGA_ACAD FOR COLEGIO.CARGA_ACAD;
CREATE PUBLIC SYNONYM CO_CARGO FOR COLEGIO.CARGO;
CREATE PUBLIC SYNONYM CO_COLEGIO FOR COLEGIO.COLEGIO;
CREATE PUBLIC SYNONYM CO_CURSO FOR COLEGIO.CURSO;
CREATE PUBLIC SYNONYM CO_ENTIDAD_BANCARIA FOR COLEGIO.ENTIDAD_BANCARIA;
CREATE PUBLIC SYNONYM CO_ESTUDIANTE FOR COLEGIO.ESTUDIANTE;
CREATE PUBLIC SYNONYM CO_GRADO FOR COLEGIO.GRADO;
CREATE PUBLIC SYNONYM CO_MATRICULA FOR COLEGIO.MATRICULA;
CREATE PUBLIC SYNONYM CO_MUNICIPIO FOR COLEGIO.MUNICIPIO;
CREATE PUBLIC SYNONYM CO_PAGO FOR COLEGIO.PAGO;
CREATE PUBLIC SYNONYM CO_PAGOS_2020 FOR COLEGIO.PAGOS_2020;
CREATE PUBLIC SYNONYM CO_PERSONA FOR COLEGIO.PERSONA;
CREATE PUBLIC SYNONYM CO_PERSONA_MUJER FOR COLEGIO.PERSONA_MUJER;
CREATE PUBLIC SYNONYM CO_PROFESOR FOR COLEGIO.PROFESOR;
CREATE PUBLIC SYNONYM CO_TITULOPROF FOR COLEGIO.TITULOPROF;