/*
    Ejercicio 5.
*/
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 

CREATE TABLESPACE tb_backup DATAFILE 'dfile_backup' SIZE 20M AUTOEXTEND ON NEXT 10M;

CREATE USER usr_backup DEFAULT TABLESPACE tb_backup TEMPORARY TABLESPACE temp;

GRANT BACKUP ANY TABLE TO usr_backup;

ALTER USER usr_backup QUOTA 100M ON tb_backup;