/*

    CONSULTAR LAS ASIGNATURAS A CARGO DE UN PROFESOR, DESPLEGAR:
    
    -NUMERO DOCUMENTO, 
    -NOMBRE Y APELLIDOS DEL PROFESOR
    -NOMBRE DE LAS ASIGNATURAS ASIGNADAS
    
    SOLO DE LAS ASIGNATURAS CORRESPONDIENTES AL AÑO ACADEMICO DEL 2020

*/
SELECT 
    PR.NUMDOC,
    INITCAP(TRIM(PE.NOMBRE3) ||' '|| TRIM(PE.APELLIDO3)) AS NOMBRE_APELLIDO,
    A.NOMBREASIG
FROM
    PROFESOR PR
INNER JOIN
    PERSONA PE
  ON
    PR.NUMDOC = PE.NUMDOC
INNER JOIN
    CARGA_ACAD C
  ON
    PR.COPROF = C.COPROF
INNER JOIN
    ASIGNATURA A
  ON
    C.COASIG = A.COASIG
WHERE
    C.ANOACAD = 2020;
    
    