/*

    CREAR UNA TABLA DE NOMBRE PERSONA_MUJER CON LA ESTRUCTURA NECESARIA PARA ALMACENAR:

    - EN UN MISMO CAMPO EL NOMBRE Y APELLIDO DE LA PERSONA
    - TIPO DOCUMENTO
    - NUMERO DOCUMENTO

    ESTA TABLA SE DEBE LLENAR CON LOS REGISTROS DE LA TABLA PERSONA QUE PERTENEZCAN AL GENERO FEMENINO

*/

CREATE TABLE "PERSONA_MUJER" (
    "TIPODOC"          CHAR(2 BYTE),
    "NUMDOC"           NUMBER(10, 0),
    "NOMBRE_APELLIDO"  VARCHAR2(50)
);

INSERT INTO PERSONA_MUJER SELECT TIPODOC, NUMDOC, INITCAP(TRIM(nombre3 || ' ' || apellido3)) FROM PERSONA WHERE GENERO3 = 'F';
