/*

    CONSULTAR LISTADO DE ESTUDIANTES MATRICULADOS, DESPLEGAR:
    
    -CODIGO DEL ESTUDIANTE
    -NOMBRE Y APELLIDOS
    -CODIGO DEL GRADO
    -AÑO ACAD?MICO
    
    SOLO DE LAS MATRICULAS CORRESPONDIENTES AL AÑO ACADEMICO DEL 2020

*/
SELECT 
    E.COEST,
    INITCAP(TRIM(P.NOMBRE3) || ' ' || TRIM(P.APELLIDO3)) AS NOMBRE_APELLIDO,
    M.COGRA,
    M.ANOACAD
FROM
    ESTUDIANTE E
INNER JOIN
    PERSONA P
  ON
    E.NUMDOC = P.NUMDOC
INNER JOIN
    MATRICULA M
  ON
    E.COEST = M.COEST
WHERE
    M.ANOACAD = 2020;