/*

    ACTUALIZAR SOBRE LA TABLA "PAGOS" EL VALOR DEL PAGO AUMENTANDOLO EN UN 40%, 
    SOLO SI EL VALOR DEL PAGO ES MAYOR A 240000, 
    Y SI EL PAGO LE  CORRESPONDE A UN ESTUDIANTE DEL "COLEGIO UCC" CODIGO 99

*/

UPDATE
    PAGO P
SET
    P.VALORPAG = P.VALORPAG + (P.VALORPAG * 0.4)
WHERE
    P.NUPAG
IN
(
SELECT 
    P.NUPAG 
FROM PAGO P
INNER JOIN 
    MATRICULA M
  ON
    P.NUPAG = M.NUPAG
INNER JOIN
    ESTUDIANTE E
  ON
    M.COEST = E.COEST
INNER JOIN
    COLEGIO C
  ON
    E.COCOLEGIO = C.COCOLEGIO
WHERE
    C.NOMBRECOLEGIO = 'Colegio UCC'
);