/*

    ELIMINAR REGISTROS DE LA TABLA PAGOS_2020, 
    DONDE EL NOMBRE DE LA ENTIDAD BANCARIA TENGA MAS DE 10 CARACTERES

*/
DELETE 
FROM 
    PAGOS_2020 
WHERE 
    LENGTH(NOMBREENT) > 10;