/*

    EL SISTEMA DEBERA GENERAR UN LISTADO DE PROFESORES, DESPLEGAR:
    
    -NOMBRE Y APELLIDOS DEL PROFESOR
    -DESCRIPCION DEL CARGO
    -EL TITULO PROFESIONAL ASIGNADO

*/
SELECT 
    INITCAP(TRIM(PE.NOMBRE3) || ' ' || TRIM(PE.APELLIDO3)) AS NOMBRE_APELLIDO,
    INITCAP(C.NOMBRECARGO) AS DESCRIPCION_CARGO,
    INITCAP(T.TITULOPROF2) AS TITULO_PROFESIONAL
FROM
    PERSONA PE
INNER JOIN
    PROFESOR PR
  ON
    PE.NUMDOC = PR.NUMDOC
INNER JOIN
    CARGO C
  ON
    PR.IDCARGO = C.IDCARGO
INNER JOIN
    TITULOPROF T
  ON 
    PR.IDTITULO = T.IDTITULO;