/*

    ACTUALIZAR LA DIRECCION DE LAS ENTIDADES BANCARIAS, PASANDO LA DIRECCION A MINUSCULA, 
    SOLO SI EN EL NOMBRE DE LA ENTIDAD BANCARIA EXISTE LA PALABRA 'BANCO'
    SE DEBEN CONTEMPLAR LAS VARIACIONES ENTRE MINUSCULA Y MAYUSCULA.

*/

UPDATE 
    ENTIDAD_BANCARIA 
SET 
    DIRECC = LOWER(DIRECC) 
WHERE 
    LOWER(NOMBREENT) 
LIKE 
    '%banco%';