/*

    CREAR UNA TABLA DE NOMBRE PAGOS_2020 CON LA ESTRUCTURA NECESARIA PARA ALMACENAR:
    
    - EL NOMBRE DE LA ENTIDAD DONDE SE REALIZO EL PAGO
    - FECHA QUE SE REALIZO EL PAGO
    - EL VALOR TOTAL DE LOS PAGOS REALIZADOS PARA ESA FECHA
    
    ESTA SE DEBE LLENAR SOLO CON LOS PAGOS REALIZADOS EN EL A?O 2020

*/
CREATE TABLE "PAGOS_2020" (
    "NOMBREENT"      VARCHAR2(50),
    "FECHAPAG"       DATE,
    "VALORPAGTOTAL"  NUMBER(10)
);

INSERT INTO PAGOS_2020 
SELECT 
    EB.NOMBREENT, P.FECHAPAG, SUM(P.VALORPAG)
FROM 
    PAGO P 
INNER JOIN 
    ENTIDAD_BANCARIA EB
  USING(coentban)
WHERE
    TRUNC(P.FECHAPAG) >= TO_DATE('01-01-2020', 'dd-mm-yyyy')
  AND
    TRUNC(P.FECHAPAG) <= TO_DATE('31-12-2020', 'dd-mm-yyyy')
GROUP BY EB.NOMBREENT, P.FECHAPAG
ORDER BY P.FECHAPAG;
